version: "3.4"

services:
  af_manylinux_2_28_base:
    build:
      context: ./arrayfire/manylinux/dev_base
    image: af/manylinux/dev_base

  af_manylinux_2_28_deps:
    build:
      context: ./arrayfire/manylinux/dependencies
    image: af/manylinux/dependencies
    depends_on:
      - af_manylinux_2_28_base

  af_manylinux_2_28_cuda_12.8:
    build:
      context: ./arrayfire/manylinux/cuda_deps
      args:
        AF_CUDA_VERSION: 12-8
    image: af/manylinux/cuda:12.8
    depends_on:
      - af_manylinux_2_28_deps

  af_manylinux_2_28_arrayfire_mkl:
    image: af/manylinux/cuda:12.8
    depends_on:
      - af_manylinux_2_28_cuda_12.8
    volumes:
      - /home/arrayfire/build_dockers/arrayfire/scripts:/scripts
      - /home/arrayfire/build_dockers/build_manylinux_arrayfire_mkl_2025_cuda_12_8:/usr/src
    stdin_open: true
    tty: true
    command: "/scripts/build_arrayfire.sh --build-type RelWithDebInfo 
             --package-type STGZ --cuda-arch \"5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;9.0+PTX\""

  af_manylinux_2_28_arrayfire_openblas:
    image: af/manylinux/cuda:12.8
    depends_on:
      - af_manylinux_2_28_cuda_12.8
    volumes:
      - /home/arrayfire/build_dockers/arrayfire/scripts:/scripts
      - /home/arrayfire/build_dockers/build_manylinux_arrayfire_openblas_cuda_12_8:/usr/src
    stdin_open: true
    tty: true
    command: "/scripts/build_arrayfire.sh --build-type RelWithDebInfo 
             --package-type STGZ --cuda-arch \"5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;9.0+PTX\" --no-mkl"

  af_ubuntu_22_04_base:
    build:
      context: ./arrayfire/ubuntu/dev_base
      args:
        UBUNTU_LTS_VERSION: 22.04
    image: af/ubuntu/dev_base

  af_ubuntu_22_04_deps:
    build:
      context: ./arrayfire/ubuntu/dependencies
    image: af/ubuntu/dependencies
    depends_on:
      - af_ubuntu_22_04_base

  af_ubuntu_22_04_cuda_12.8:
    build:
      context: ./arrayfire/ubuntu/cuda_deps
      args:
        AF_CUDA_VERSION: 12-8
    image: af/ubuntu/cuda:12.8
    depends_on:
      - af_ubuntu_22_04_deps

  af_ubuntu_22_04_arryfire_mkl:
    image: af/ubuntu/cuda:12.8
    depends_on:
      - af_ubuntu_22_04_cuda_12.8
    volumes:
      - /home/arrayfire/build_dockers/arrayfire/scripts:/scripts
      - /home/arrayfire/build_dockers/build_ubuntu_arrayfire_mkl_2025_cuda_12_8:/usr/src
    stdin_open: true
    tty: true
    command: "/scripts/build_arrayfire.sh --build-type RelWithDebInfo 
             --package-type DEB --cuda-arch \"5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;9.0+PTX\""

  af_ubuntu_22_04_openblas_cuda_12.8:
    image: af/ubuntu/cuda:12.8
    depends_on:
      - af_ubuntu_22_04_cuda_12.8
    volumes:
      - /home/arrayfire/build_dockers/arrayfire/scripts:/scripts
      - /home/arrayfire/build_dockers/build_ubuntu_arrayfire_openblas_cuda_12_8:/usr/src
    stdin_open: true
    tty: true
    command: "/scripts/build_arrayfire.sh --build-type RelWithDebInfo 
             --package-type DEB --cuda-arch \"5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;9.0+PTX\" --no-mkl"

